[package]
name = "aoc_2023_10"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-util = { git = "https://github.com/FilipAndersson245/advent_of_code" }
anyhow = "1.0.75"
itertools = "0.12.0"
glam = "0.24.2"
