[package]
name = "aoc_2023_15"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-util = { git = "https://github.com/FilipAndersson245/advent_of_code" }
anyhow = "1.0.75"
itertools = "0.12.0"
indexmap = "2.1.0"
linked-hash-map = "0.5.6"
